# Copyright 2025 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: 'Build'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: 'read'

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Checkout Code'
        uses: 'actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd' # v6

      - name: 'Set up bazel'
        uses: 'bazel-contrib/setup-bazel@083175551ceeceebc757ebee2127fde78840ca77' # 0.18.0
        with:
          bazelisk-cache: true
          disk-cache: true
          external-cache: true
          repository-cache: true

      - name: 'Build'
        run: 'bazel build //...'

      - name: 'Test'
        run: 'bazel test //...'
